apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    NodePort: 30007
  selector:
    app: swiggy-app
